export { Home } from "./Home";
export { RestartModal } from "./RestartModal";
export { Navigation } from "./Navigation";
export { QuizPage } from "./QuizPage";
export { Result } from "./Result";
export { Rules } from "./Rules";
export { ScoreBoard } from "./ScoreBoard";
export { Footer } from "./Footer";
export { Login } from "./Login";
export { Signup } from "./Signup";
export { UserProfile } from "./UserProfile";
export {PrivateRoute} from "./PrivateRoute";
