export { Home } from "./Home";
export { RestartModal } from "./RestartModal";
export { Navigation } from "./Navigation";
export { Profile } from "./Profile";
export { QuizPage } from "./QuizPage";
export { Result } from "./Result";
export { Rules } from "./Rules";
export { ScoreBoard } from "./ScoreBoard";
export { Footer } from "./Footer";
